FROM docker.io/nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip python3-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir --break-system-packages \
    torch torchvision --index-url https://download.pytorch.org/whl/cu128

RUN pip3 install --no-cache-dir --break-system-packages \
    nibabel numpy pandas

VOLUME ["/app"]
VOLUME ["/data"]
VOLUME ["/experiments"]

WORKDIR /app

ENTRYPOINT ["python3", "app.py"]